{
  "comments": [
    {
      "key": {
        "uuid": "a16f575d_adde8181",
        "filename": "smutLayer/changeVM.py",
        "patchSetId": 2
      },
      "lineNbr": 747,
      "author": {
        "id": 1010466
      },
      "writtenOn": "2017-07-31T17:49:55Z",
      "side": 1,
      "message": "So I\u0027m curious here why we just use the results[\u0027response\u0027] in our error message and not a custom error message?  I think this does not get set in disableEnableDisk, but rather by execCmdThruIUCV.  So while that\u0027s going to give a nice message about what IUCV command was being issued on the guest and what output it got, it might be nice to wrapper that in \"tried to execute a command to detach disk from guest, failure message....\"",
      "revId": "794742bef8e423232311b5526f0bfd04c370027e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "960cfe30_fa8a3468",
        "filename": "smutLayer/changeVM.py",
        "patchSetId": 2
      },
      "lineNbr": 747,
      "author": {
        "id": 1008725
      },
      "writtenOn": "2017-07-31T19:16:49Z",
      "side": 1,
      "message": "The message produced by execCmdThruIUCV indicates the command that failed, the returned information, and out of the command.  This allows execCmdThruIUCV to produce a message for a command that failed AND for any transmission problems.  Thus, we do not have put write additional code every where we invoke execCmdThruIUCV to determine whether the command failed or something went wrong related to IUCV, IUCV client or IUCV daemon.",
      "parentUuid": "a16f575d_adde8181",
      "revId": "794742bef8e423232311b5526f0bfd04c370027e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "4d0630ac_e34c828d",
        "filename": "smutLayer/vmUtils.py",
        "patchSetId": 2
      },
      "lineNbr": 62,
      "author": {
        "id": 1010466
      },
      "writtenOn": "2017-07-31T17:49:55Z",
      "side": 1,
      "message": "Why is the last number 0 and then we test for not 0?  Why not let it just fall out of the loop in that case?  Seems an inefficent use of a for loop.",
      "revId": "794742bef8e423232311b5526f0bfd04c370027e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "d502e3e3_0b371199",
        "filename": "smutLayer/vmUtils.py",
        "patchSetId": 2
      },
      "lineNbr": 62,
      "author": {
        "id": 1008725
      },
      "writtenOn": "2017-07-31T19:16:49Z",
      "side": 1,
      "message": "The 0 allowed for one final immediate retry.  I will remove it.",
      "parentUuid": "4d0630ac_e34c828d",
      "revId": "794742bef8e423232311b5526f0bfd04c370027e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8a6f9fd8_f909e838",
        "filename": "smutLayer/vmUtils.py",
        "patchSetId": 2
      },
      "lineNbr": 71,
      "author": {
        "id": 1010466
      },
      "writtenOn": "2017-07-31T17:49:55Z",
      "side": 1,
      "message": "I think you want to set \u0027response\u0027 not \u0027results\u0027.",
      "revId": "794742bef8e423232311b5526f0bfd04c370027e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "6347e602_8f628382",
        "filename": "smutLayer/vmUtils.py",
        "patchSetId": 2
      },
      "lineNbr": 71,
      "author": {
        "id": 1008725
      },
      "writtenOn": "2017-07-31T19:16:49Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "8a6f9fd8_f909e838",
      "revId": "794742bef8e423232311b5526f0bfd04c370027e",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}